logging:
  level:
    root: info

dubbo:
  application:
    name: dubbo-tri-bistream-test
    register-mode: instance
    protocol: tri
  scan:
    base-packages: org.example.dubbo
  protocol:
    name: tri
    port: 50051
    serialization: protobuf
  registry:
    address: zookeeper://localhost:2181
    use-as-metadata-center: true
    use-as-config-center: true
  provider:
    delay: -1
#    timeout: 3000
    retries: 0
#    prefer-serialization: protobuf
  consumer:
    check: false
